name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm test
    - run: ./build prod
      env:
        CI: true
    - name: Extract Version
      shell: bash
      id: extract-version
      run: echo "::set-output name=version::$(node version.js)"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract-version.outputs.version}}
        release_name: Release ${{ steps.extract-version.outputs.version}}
        draft: true
        prerelease: true
    - name: Upload Release Asset
      id: upload-module-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/TokenHotbar.zip
        asset_name: TokenHotbar.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-manifest
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module.json
        asset_name: module.json
        asset_content_type: application/json
