name: TokenHotbar CI

on:
  push:
    tags:
        - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Update Version
      shell: bash
      id: set-version
      run: echo "::set-output name=version::$(node ./.github/workflows/set-version.js ${{ github.ref }})"
    - name: Transform Package Title
      shell: bash
      id: transform-package-title
      run: node ./.github/workflows/transform-module-json.js
    - name: Verify download channel
      shell: bash
      id: check-download
      run: node ./.github/workflows/check-download.js
    - run: npm install
    - run: npm test
    - run: ./build prod
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        name: Release ${{ steps.set-version.outputs.version}}
        draft: false
        prerelease: ${{ endsWith(steps.set-version.outputs.version, 'a') }}
        bodyFile: './PATCH_NOTES.md'
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './dist/TokenHotbar.zip,./module.json'
